### ISSUE TITLE
Feature Request - Success notification when editing a Class

### ISSUE THREAD

**Issue by IvanFrescas** [Josefrancasrod/school_app#33]
**Summary:**
When we create a class and edit a field (teacher name or color) the data is saved, but there isn't a notice indicating that it was saved correctly.
A Toast, a Dialog or something similar would be nice :) 

**Steps to reproduce:**
- Add a new class 
- Fill in the data
- Save the class
- Click hamburger menu
- Go to "My classes"
- Select a class and change any value
- Click Save button

**Expected Result**
The information is saved and the application display a notification about it.
 
**Actual Result**
The information is saved.

**Comment by Josefrancasrod** [comment]
Hi, Ivan!

It's a great idea. I create an alert when you add/edit a class, you can check the **Pull Request #37**.
I will close this issue.

Thanks for the support.
